version: "3.7"
services:

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DOCKER=1
            - XDEBUG_CONFIG=remote_host=host.docker.internal
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
